// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryAPI.Context;

namespace SalaryAPI.Migrations
{
    [DbContext(typeof(ContextoPrediccion))]
    [Migration("20210123215643_Version Inicial")]
    partial class VersionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SalaryAPI.Models.Prediccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estatus")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Salario")
                        .HasColumnType("REAL");

                    b.Property<double>("TiempoExperiencia")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
